#%RAML 1.0 NamedExample
{
  "code": 400,
  "message": "Bad Request",
  "description": "The requested payload doesn't comply with API spec",
  "datetime": "2021-11-11T09:00:00Z",
  "transactionID": "4bc789-34hjd-34343gf-fgjko98"  
}